### ISSUE TITLE
OCaml Binding for IP2Location LITE

### ISSUE THREAD

**Issue by m-cameron** [fxfactorial/ocaml-maxminddb#1]
Do you have any OCaml binding support for IP2Location LITE binary format?

http://lite.ip2location.com

**Comment by fxfactorial** [comment]
No, but would you benefit from it? Would you use the OCaml bindings?

**Comment by fxfactorial** [comment]
I think you're trying to get programmers to do free labor for your company, hint your public activity is public.

**Comment by DavidePastore** [comment]
@fxfactorial :+1: for your words
